#pragma once

enum {
    ERR_OPERATION_FAILED = -1,
    ERR_FILE_NOT_EXISTS = 1,
    ERR_FILE_EXISTS,
    ERR_FILE_NO_PERMISSION,
    ERR_FILE_TYPE_MISMATCH,
    ERR_DIRECTORY_NOT_EMPTY,
    ERR_FD_INVALID,
};
